### ISSUE TITLE
Should we implement this as a perl module?

### ISSUE THREAD

**Issue by ericcurtin** [spook/ssl-add2bundle#2]
A perl module might be handy so you can integrate this with another
perl script without calling system, backticks, etc. A script that uses
this alongside it also, maybe?

**Comment by spook** [comment]
Thanx Eric, a good idea.
I like the idea of a single-file for a utility; but the single file can contain both the main and the module.  This way we get the best of both worlds.  Right now, I've tried to make it so someone can peel-out the add_bundle() sub if they want to use it standalone.  The module would be cleaner.
